name: DnD LaTeX compilation
on: [push]
description: Compiles latex documents using xelatex.
author: Tristan

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile all .tex files in the working directory
        uses: dante-ev/latex-action@master
        with:
          pre_compile: |
            for texfile in ./lib/dnd/characters/*.tex; do
              echo "Compiling $texfile"
              xelatex -interaction=nonstopmode "$texfile"
            done
          root_file: "" # Leave this empty
          working_directory: ./characters
          compiler: xelatex
