name: DnD LaTeX compilation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: dante-ev/latex-action@v2.0.0
        with:
          texlive_version: scheme-small

      - name: Download DND-5e-LaTeX-Template repository
        run: |
          wget https://github.com/evanbergeron/DND-5e-LaTeX-Template/archive/refs/heads/master.zip
          unzip master.zip

      - name: Set up LaTeX packages
        run: |
          mkdir -p latex_packages
          cp -r DND-5e-LaTeX-Template-master/* latex_packages/

      - name: Compile LaTeX documents
        run: |
          mkdir -p output
          for texfile in ./characters/*.tex; do
            outputfile="output/$(basename -s .tex $texfile).pdf"
            echo "Compiling $texfile -> $outputfile"
            TEXINPUTS=./latex_packages//: xelatex -interaction=nonstopmode -output-directory=output "$texfile"
          done
