name: DnD LaTeX compilation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install TeX Live XeTeX package
        run: sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-extra

      - name: Download DND-5e-LaTeX-Template repository and copy the content
        run: |
          wget https://github.com/evanbergeron/DND-5e-LaTeX-Template/archive/refs/heads/master.zip
          unzip master.zip
          mkdir -p latex_packages
          cp -r DND-5e-LaTeX-Template-stable/* latex_packages/

      - name: Compile all .tex files in the working directory
        run: |
          mkdir -p output
          for texfile in ./characters/*.tex; do
            outputfile="output/$(basename -s .tex $texfile).pdf"
            echo "Compiling $texfile -> $outputfile"
            TEXINPUTS=./latex_packages//: xelatex -interaction=nonstopmode -output-directory=output "$texfile"
          done

      - name: Compile the main document
        uses: dante-ev/latex-action@master
        with:
          root_file: "" # Leave this empty
          working_directory: ./characters
          compiler: xelatex
