name: DnD LaTeX compilation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install TeX Live packages from packages.txt
        run: |
          sudo apt-get update
          sudo apt-get install -y $(cat packages.txt | tr '\n' ' ')

      - name: Download DND-5e-LaTeX-Template repository and copy the content
        run: |
          wget https://github.com/evanbergeron/DND-5e-LaTeX-Template/archive/refs/heads/master.zip
          unzip master.zip
          mkdir -p latex_packages
          cp -r DND-5e-LaTeX-Template-stable/* latex_packages/

      - name: Compile all .tex files in the characters directory
        run: |
          mkdir -p output
          for texfile in ./characters/*.tex; do
            outputfile="output/$(basename -s .tex $texfile).pdf"
            echo "Compiling $texfile -> $outputfile"
            TEXINPUTS=./latex_packages//: xelatex -interaction=nonstopmode -output-directory=output -no-shell-escape "$texfile"
          done

      - name: Compile the main document
        uses: dante-ev/latex-action@master
        with:
          root_file: "" # Leave this empty
          working_directory: ./characters
          compiler: xelatex
